

#update travis file
sudo: required
language: node_js
node_js:
  - "10.15.3"
script:
  - unset CI
  - npm run build
  - npm run post-build

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY_ID
  bucket: "aion-staking-info-bot"
  skip_cleanup: true
  
  


